"""Stable reason codes for sync policy decisions."""
PRIVACY_RESTRICTED = "privacy_restricted"
OPERATOR_LOCAL_ONLY = "operator_local_only"
OPERATOR_AUTO = "operator_auto"
OPERATOR_APPROVAL_REQUIRED = "operator_approval_required"
OPERATOR_NOTE_REQUIRES_REVIEW = "operator_note_requires_review"
HIGH_CONFIDENCE_INCIDENT = "high_confidence_incident"
INCIDENT_CONFIDENCE_BELOW_THRESHOLD = "incident_confidence_below_threshold"
ROUTINE_OBSERVATION_LOCAL_ONLY = "routine_observation_local_only"
FLEET_SAFE_LEARNED_FACT = "fleet_safe_learned_fact"
DEFAULT_LOCAL_ONLY = "default_local_only"
